### ISSUE TITLE
Can't load add-in

### ISSUE THREAD

**Issue by kelvinchanky** [boozallen/argo#14]
Initialization [Error] DnaLibrary AutoOpen Error : TargetInvocationException - Exception has been thrown by the target of an invocation.

I've tried all the troubleshooting at https://github.com/boozallen/argo/wiki/Troubleshooting  but nothing seems to get the addin to load. Any help? Using excel 2010 32-bit. My other addins (Macabacus, FRED & CapitalIQ) all work fine.

**Comment by todd-skinner** [comment]
Hi, thanks for your post. This is an issue we are continuing to investigate. There's another thing I'd be curious for you to try that wasn't in the troubleshooting page. Navigate to **File > Options > Trust Center** and open the **Trust Center Settings**. Then click on the **Trusted Locations** tab in the Trust Center window. Click the **Add new location** button, add the Argo folder location, and press **OK**. Then restart Excel and try to load Argo again. Let me know if this solves the error.

**Comment by kelvinchanky** [comment]
Todd, I've disabled all security settings and placed the addin into a trusted folder & also made BAH a trusted publisher, yet that error message still pops up.
I just tried Argo on my home computer though, and it works fine on Office 2013 professional plus (32-bit). I don't know if there are conflicts with other addins (i doubt it), or if there are restrictions on the work computer that prevent Argo from running.

**Comment by kelvinchanky** [comment]
I tried loading just the COM add-in (without loading it in addins) and excel does not let me do that. It says "Not loaded. A runtime error occurred during the loading of the COM add-in."

**Comment by todd-skinner** [comment]
Hi Kelvin,

Thanks for the updates. Argo 4 needs to be loaded in Excel Add-ins not COM Add-ins so that error is expected. We are still investigating the TargetInvocationException error. It's a tricky thing to debug since we haven't found a computer yet that can replicate the problem. The error seems to sometimes occur on government computers or computers loaded with antivirus and privilege management software. Are you running any security software like Symantec Endpoint Protection on your work computer?

**Comment by kelvinchanky** [comment]
Hi Todd,

Yes, our endpoint protection likely comes with privilege management (Cylance Protect). I'm having our local IT guy take a look and see if he can run it too.

**Comment by todd-skinner** [comment]
Hi Kelvin,

We just pushed out a new version of Argo that should provide a more informative error message than the standard TargetInvocationException message. Can you try downloading this new version and let us know what error message you get when you try to load it? This should hopefully help us isolate the point of failure. The download link from your getargo@bah.com email will always give you the most recent version (in this case 4.1.2).

**Comment by kelvinchanky** [comment]
Thanks Todd, here are the error messages. I definitely do have all the .dlls (including statlib3.dll) in the same folder as the XLL addin.

[Excel 14x86;CLR 4.0.30319.18444] System.IO.FileNotFoundException: Could not load file or assembly 'StatLib3.dll' or one of its dependencies. The specified module could not be found.

at ArgoXllDev.ThisAddIn.AutoOpen()
at ArgoXllDev.StaticXLLRefs.LoadStatLib()
at System.Reflection.Assembly.Load(String assemblyString)
at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) 
![image](https://cloud.githubusercontent.com/assets/28020044/25551174/e575835e-2c4e-11e7-9e2c-92c9dc71c7b6.png)


Our local IT guy couldn't load it too and I'm in the process of escalating it to our infrastructure network team as well.

**Comment by todd-skinner** [comment]
Hi Kelvin,

Thanks for getting back so quickly. We've added another troubleshooting step that may address that error. Windows Group Policies may be configured to block files downloaded from the internet. Check out the troubleshooting page again for instructions on how to unblock these files:
https://github.com/boozallen/argo/wiki/Troubleshooting#files-downloaded-from-the-internet-are-blocked-by-windows-group-policies

**Comment by kelvinchanky** [comment]
Sounds good, let me get our IT guy to test it out.

**Comment by kelvinchanky** [comment]
It appears our IT guy could install it on a computer without security software, so the dlls are likely getting blocked by our security software rather than windows group policy. Thank you for the help! Now I'll need to discuss with IT on how to get it exempted.

**Comment by esgoff** [comment]
Hi,

I'm having the same or a similar problem as kelvinchanky, but my IT guy tried to install on a computer without out security software and still got the same error.  Any fixes?

[Excel 15x86;CLR 4.0.30319.42000] System.IO.FileLoadException: Could not load file or assembly 'StatLib3' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))

at ArgoXllDev.StaticXLLRefs.LoadStatLib()
at System.Reflection.Assembly.Load(String assemblyString)
at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at ArgoXllDev.ThisAddIn.AutoOpen()

![image](https://cloud.githubusercontent.com/assets/28900445/26361061/cdc0c2fc-3fa7-11e7-8c61-31ba6a523a1a.png)

**Comment by todd-skinner** [comment]
@esgoff If there's no security software on your computer, I'd point you towards this [troubleshooting section](https://github.com/boozallen/argo/wiki/Troubleshooting#systemiofileloadexception-could-not-load-file-or-assembly-statlib3-or-one-of-its-dependencies) if you haven't read through it already. We have added a few things since the issue was opened.

**Comment by esgoff** [comment]
Thanks Todd,  another IT person figured out the files were locked because they were from the internet.  He unlocked them and that fixed it, Thanks so much!  Can't wait to use the program

**Comment by defencedog** [comment]
@Win8.1 x64; Office 2010 x32

AND

@Linux WINE 1.8; Office 2007 SP3 x32 (Many MACROs like Oracle CrystallBall running flawlessly)

I have the same issue, please do help me

`[Excel 12x86;CLR 4.0.30319.1] System.IO.FileLoadException: Could not load file or assembly 'StatLib3.dll' or one of its dependencies. Message 0x not found in file . (Exception from HRESULT: 0x8007013D)

at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
`
When I right click StatLib3.dll there is no UNBLOCK option in WIN8.1 x64

**Comment by todd-skinner** [comment]
Hi @defencedog. I assume you went through the [troubleshooting steps](https://github.com/boozallen/argo/wiki/Troubleshooting) already? Be aware that unblock option may be disabled due to your organization's IT policies.

We have just pushed out version 4.1.3. Argo can now be downloaded as a self-extracting zip file instead of a normal zip file. Hopefully, now that the files come from an executable instead of an internet zip file, they won't get automatically blocked by Windows. Try downloading the new Argo version and see if you can add it on Excel now. You can use your same download link to get the latest version at any time.

**Comment by defencedog** [comment]
@Win8.1 x64; Office 2010 x32 ...version 4.1.3

working hurray!

@linux WINE 1.8; Office 2007 SP3 x32

terminal shows dependancy error 
`unimplemented function api-ms-win-crt-runtime-l1-1-0.dll._initialize_onexit_table,`
above is a well documented error. The same error happened after installing NumXL but it was SOLVED
```
wine winecfg >libraries (require vcrun2015 to be installed preferably by winetricks)
add these
api-ms-win-crt-runtime-l1-1-0
api-ms-win-crt-heap-l1-1-0
api-ms-win-crt-locale-l1-1-0
api-ms-win-crt-stdio-l1-1-0
api-ms-win-crt-time-l1-1-0
ucrtbase
vcruntime140

then run (VC6 library)
wine vbrun60sp6.exe
```

used work around of installing vcrun2015 through winetricks ...via winecfg registered absent libraries ...but top no avail
:( ...not working in short

**Comment by todd-skinner** [comment]
Glad to see it's working on your Windows 8 system! We have never tested Argo on WINE before so I'm afraid I can't offer much support in that area. If you or anyone else figures out a way to run Argo in WINE, post your steps here and the Argo team will be happy to post the details to our wiki documentation.

**Comment by kelvinchanky** [comment]
Todd, whatever you did with version 4.1.3 is great because it now works for me on my office laptop. Everything's good now, thanks! The exe file must have gotten past the automated blocking of everything in a .zip file.

**Comment by temnikoff** [comment]
Hello. May somebody please fix the download link or share the argo installer with me?
