### ISSUE TITLE
Simulation won't run

### ISSUE THREAD

**Issue by esgoff** [boozallen/argo#16]
I've successfully run the demo Excel file on your website, but when I try to run my own model I get this error.  The work around to switching to Native Excel does work but it runs extremely slowly.  What can I change in my model to avoid this problem?  Using the workaround Native Excel is so slow it is not a viable option.  Thanks so much for any help!

[Excel 15x86;CLR 4.0.30319.42000] System.FormatException: Input string was not in a correct format.

at ArgoXllDev.RegisterUDFLib.__Argo_BuildPrecedents__()
at ArgoXllDev.PrecedentMiner.BuildPrecedentChain()
at ArgoXllDev.ExcelAddressUtil.ParsePositionInfo(String arg, IntPtr defaultsheetid, Int32& r1, Int32& r2, Int32& c1, Int32& c2, String& workbook, String& worksheet)
at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)

**Comment by blakeboswell** [comment]
As a reference, this issue looks similar to the (unresolved) issue brought to the google group: https://groups.google.com/forum/#!topic/argo-users/1djK7cn9M74

**Comment by todd-skinner** [comment]
This error seems to occur if there are ranges that select entire columns or rows (i.e. "A:A", "1:1", "A:C", etc) and Argo does not support that format. Please format your references to explicitly include columns _and_ rows so that only the cells in use are selected. For example, use something like "A1:B20" instead of "A:B". We will be pushing out an update later today that will catch this error and return a more useful error message that lists the references which need to be changed. I'll update this thread when it is released.

**Comment by todd-skinner** [comment]
The latest version (4.1.3) is now released. You can use your download link to get it.
