### ISSUE TITLE
Problem when trying to create Embed charts and Tables

### ISSUE THREAD

**Issue by Majramos** [boozallen/argo#17]
When I try to create embed charts and tables this errors appear:

[Argo 4.1.3;Excel 15x86;CLR 4.0.30319.42000] System.Runtime.InteropServices.COMException: Unable to set the NumberFormat property of the Range class

at System.Dynamic.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, UInt32 argErr, String message)

at CallSite.Target(Closure , CallSite , ComObject , String )

at CallSite.Target(Closure , CallSite , Object , String )

at ArgoXllDev.ExcelSheetFrequency.BuildSingleCharts(String WbName, List`1 cells, Boolean cdf, Boolean hist, Boolean hist2, Boolean rcdf, Boolean isdynamic)

at ArgoXllDev.ExcelSheetFrequency.CreateCharts(String WbName, List`1 cells, Boolean cdf, Boolean hist, Boolean hist2, Boolean rcdf, Boolean multicdf, Boolean isdynamic)

at ArgoXllDev.SelectFrequencyCharts.btnCreateCharts_Click(Object sender, EventArgs e)

I'm using Excel 2013

**Comment by brandonherzog** [comment]
Hi @Majramos, thanks for the bug report!

I am unable to reproduce the issue on my end; are you able to provide a worksheet that causes the issue?

Also, are you using an Excel version with a locale that uses the comma separator for decimals? We've seen issues with this in the past as, unfortunately, Argo was initially built to only support the English (USA) locale.

**Comment by nounours77** [comment]
I post here, since I suspect that my issue is connected to the one Majramos  reported. I'm using German locale. I attach my simple example. Happy to assist if I can.

Gilbert

********
Hi,

I worked myself through the Tutorial, and everything looks fine. What a great plugin!
Only point: I found two issues (crashes) on plotting the results. Maybe connected to my different language local (using german?). If I can assist you in performing tests, I will be happy to help.
Keep on your great work!
Gilbert


1) While drawing a sensitivity graph:
[Argo 4.1.3;Excel 14x64;CLR 4.0.30319.36415] System.Runtime.InteropServices.COMException: Ausnahme von HRESULT: 0x800A03EC
bei ArgoXllDev.OatForm.btnOK_Click(Object sender, EventArgs e)
bei ArgoXllDev.OatSensitivityAnalysis.RunOFATSensitivitySimulation()
bei ArgoXllDev.OatSensitivityAnalysis.createReport(List`1 outputs, Double basecase)
bei Microsoft.Office.Interop.Excel._Worksheet.get_Range(Object Cell1, Object Cell2)

2) When drawing a Embedded Chart:
[Argo 4.1.3;Excel 14x64;CLR 4.0.30319.36415] System.Runtime.InteropServices.COMException: Die NumberFormat-Eigenschaft des Range-Objektes kann nicht festgelegt werden.
(The NumberFormat-property of the Range-Object can not be assigned).
bei ArgoXllDev.SelectFrequencyCharts.btnCreateCharts_Click(Object sender, EventArgs e)
bei ArgoXllDev.ExcelSheetFrequency.CreateCharts(String WbName, List`1 cells, Boolean cdf, Boolean hist, Boolean hist2, Boolean rcdf, Boolean multicdf, Boolean isdynamic)
bei ArgoXllDev.ExcelSheetFrequency.BuildSingleCharts(String WbName, List`1 cells, Boolean cdf, Boolean hist, Boolean hist2, Boolean rcdf, Boolean isdynamic)
bei CallSite.Target(Closure , CallSite , Object , String )
bei CallSite.Target(Closure , CallSite , ComObject , String )
bei System.Dynamic.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, UInt32 argErr, String message)

[ArgoDemo.xlsx](https://github.com/boozallen/argo/files/1918604/ArgoDemo.xlsx)

**Comment by nounours77** [comment]
Temorary fix: I switched in the windows control panel the regional settings for number formats to "US English", and it works perfectly!!!

**Comment by blakeboswell** [comment]
Awesome!  Thanks for sharing the fix.
