### ISSUE TITLE
Embed Charts Excel 2016 Error

### ISSUE THREAD

**Issue by todd-skinner** [boozallen/argo#7]
During a training session, several students with Excel 2016 encountered an error when trying to embed charts. After selecting a distribution or result in the selection pane and clicking OK, an exception is thrown.

Here is the stack trace from the error message:
***********\* Exception Text **************
System.ArgumentException: Excel version not supported
   at ArgoXllDev.ThisAddIn.ExcelVersion.GetVersion()
   at ArgoXllDev.ExcelSheetFrequency.BuildSingleCharts(String WbName, List'1 cells, Boolean cdf, Boolean hist, Boolean hist2, Boolean rcdf, Boolean isdynamic)
   at ArgoXllDev.ExcelSheetFrequency.CreateCharts(String WbName, List'1 cells, Boolean cdf, Boolean hist, Boolean hist2, Boolean rcdf, Boolean multicdf, Boolean isdynamic)
   at ArgoXllDev.SelectFrequencyCharts.btnCreateCharts_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by brandonherzog** [comment]
Fixed in 3.1
