### ISSUE TITLE
Argo Freeze Error

### ISSUE THREAD

**Issue by todd-skinner** [boozallen/argo#8]
Some students at the training session got an error when clicking the "Freeze" button. 

**Error Message:** An item with the same key has already been added.

**Stack Trace:** 
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary'2.Insert(TKey key, TValue value, Boolean add)
   at CallSite.Target(Closure , CallSite , Dictionary'2 , String , Object )
   at ArgoXllDev.ShareArgo.Freeze()
   at ArgoXllDev.ArgoRibbon.FreezeBtnOnClick(IRibbonControl control)

**Comment by brandonherzog** [comment]
Feature removed in 3.1
