### ISSUE TITLE
Add Correlation Matrix Error

### ISSUE THREAD

**Issue by todd-skinner** [boozallen/argo#9]
Some students at the training session encountered an exception when they attempted to add a correlation matrix. They were using Excel 2016.

*************\* Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: argo formula prefix not present
   at ArgoXllDev.ExcelSheetCorrelation.InsertValCorrMatApplyFormula(String dist_formula_prefix, String valcorr_formula_prefix, String existing_formula, String matrix_formula)
   at ArgoXllDev.ExcelSheetCorrelation.CreateCorrelation(Workbook Wb, List`1 cells, Double blanket_rho, String name, Boolean lower)
   at ArgoXllDev.CorrelationSelectionForm.CreateMatrixBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by brandonherzog** [comment]
Fixed in 3.1
